#!/usr/bin/env bash

set -e

jekyll build
git checkout master
git rm -qr .
git checkout master -- .gitignore
cp -r _site/. .
rm -r _site
git add -A
git commit -m 'Publish'
git checkout source

echo Commit and push now pls
