# -*- mode: ruby -*-
# vi: set ft=ruby :

VAGRANTFILE_API_VERSION = "2"

Vagrant.configure(VAGRANTFILE_API_VERSION) do |config|
  config.vm.box = "ubuntu-14.04-amd64-vbox"
  config.vm.box_url = "https://oss-binaries.phusionpassenger.com/vagrant/boxes/latest/ubuntu-14.04-amd64-vbox.box"
  config.vm.network "forwarded_port", guest: 4873, host: 4873

  # sync data locally, so we don't lose it on destroy
  config.vm.synced_folder "sinopia_data/", "/var/sinopia", mount_options: %W{dmode=777 fmode=666}

  config.vm.provision "ansible" do |ansible|
    ansible.playbook = "test.yml"
  end
end
